
Q1- Try to create the backpropagation and feedforward in python by creating function

In [1]:
import numpy as np

xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)  # input data
y = np.array(([92], [86], [89]), dtype=float)  # output

# scale units
xAll = xAll / np.amax(xAll, axis=0)  # scaling input data
y = y / 100  # scaling output data (max test score is 100)

# split data
X = np.split(xAll, [3])[0]  # training data
xPredicted = np.split(xAll, [3])[1]  # testing data

y = np.array(([92], [86], [89]), dtype=float)
y = y / 100  # max test score is 100


class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3

        #weights
        self.W1 = np.random.randn(
            self.inputSize,
            self.hiddenSize)  # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(
            self.hiddenSize,
            self.outputSize)  # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(
            X,
            self.W1)  # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z)  # activation function
        self.z3 = np.dot(self.z2, self.W2
        )  # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3)  # final activation function
        return o

    def sigmoid(self, s):
        # activation function
        return 1 / (1 + np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o  # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(
            o)  # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(
            self.W2.T
        )  # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error * self.sigmoidPrime(
            self.z2)  # applying derivative of sigmoid to z2 error
        self.W1 += X.T.dot(
            self.z2_delta)  # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(
            self.o_delta)  # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))


NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" +
          str(np.mean(np.square(y - NN.forward(X)))))  # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.09443174]
 [0.12480145]
 [0.13866122]]
Loss: 
0.5955299395644976


# 1

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.11352662]
 [0.14605729]
 [0.16271039]]
Loss: 
0.5630212302559169


# 2

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.13763666]
 [0.17206389]
 [0.19164385]]
Loss: 
0.5243499324481039


# 3

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.16751648]
 [0.20336313]
 [0.22560279]]
Loss: 
0.4796090239257634


# 4

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.20333251]
 [0.23998744]
 [0.26400406]]
Loss: 
0.4299662620453679


# 5

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Ou

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88625005]
 [0.89356969]
 [0.86836819]]
Loss: 
0.0009113060759451576


# 99

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88654151]
 [0.89378603]
 [0.86866274]]
Loss: 
0.0009054149701313393


# 100

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88682425]
 [0.89399545]
 [0.8689487 ]]
Loss: 
0.0008998260937399331


# 101

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88709858]
 [0.89419819]
 [0.86922636]]
Loss: 
0.0008945213924891477


# 102

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88736477]
 [0.89439449]
 [0.86949602]]
Loss: 
0.0008894839826014719


# 103

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [

 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89685378]
 [0.89973966]
 [0.87949377]]
Loss: 
0.000741789604536652


# 243

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89686209]
 [0.89973049]
 [0.87950501]]
Loss: 
0.0007413398717363973


# 244

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89687024]
 [0.8997212 ]
 [0.87951609]]
Loss: 
0.0007408907284985441


# 245

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89687822]
 [0.89971179]
 [0.879527  ]]
Loss: 
0.0007404421669567792


# 246

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89688605]
 [0.89970225]
 [0.87953775]]
Loss: 
0.0007399941796119583


# 247

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.8

Predicted Output: 
[[0.89727898]
 [0.89846108]
 [0.88020538]]
Loss: 
0.0006971446096559957


# 348

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728115]
 [0.89844785]
 [0.88021011]]
Loss: 
0.0006967417284842306


# 349

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728331]
 [0.89843462]
 [0.88021482]]
Loss: 
0.0006963392435943688


# 350

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728546]
 [0.89842139]
 [0.88021953]]
Loss: 
0.0006959371545383008


# 351

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728759]
 [0.89840816]
 [0.88022421]]
Loss: 
0.0006955354608696671


# 352

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89728972]
 [0.898

 [0.89]]
Predicted Output: 
[[0.89742162]
 [0.89749222]
 [0.88053046]]
Loss: 
0.0006683739147941003


# 422

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742342]
 [0.89747936]
 [0.88053463]]
Loss: 
0.0006679992089033576


# 423

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742522]
 [0.89746651]
 [0.8805388 ]]
Loss: 
0.0006676248682777993


# 424

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742702]
 [0.89745367]
 [0.88054296]]
Loss: 
0.0006672508925129912


# 425

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89742882]
 [0.89744084]
 [0.88054712]]
Loss: 
0.0006668772812047748


# 426

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89743061

Predicted Output: 
[[0.89760474]
 [0.89621244]
 [0.88094491]]
Loss: 
0.0006316276757313257


# 525

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89760652]
 [0.89620046]
 [0.88094881]]
Loss: 
0.0006312885184532197


# 526

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8976083]
 [0.8961885]
 [0.8809527]]
Loss: 
0.0006309496863225665


# 527

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89761008]
 [0.89617654]
 [0.8809566 ]]
Loss: 
0.0006306111789662361


# 528

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89761187]
 [0.89616459]
 [0.88096049]]
Loss: 
0.0006302729960114152


# 529

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89761365]
 [0.896152

# 635

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89780429]
 [0.89493491]
 [0.88136525]]
Loss: 
0.0005958854967183907


# 636

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89780611]
 [0.89492386]
 [0.88136892]]
Loss: 
0.0005955802278778964


# 637

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89780792]
 [0.89491282]
 [0.88137259]]
Loss: 
0.000595275244841642


# 638

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89780974]
 [0.89490179]
 [0.88137626]]
Loss: 
0.0005949705472744741


# 639

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89781156]
 [0.89489077]
 [0.88137993]]
Loss: 
0.0005946661348415852


# 640

Input (scaled): 
[[0.4 0.9]
 [0.2 

Predicted Output: 
[[0.89791557]
 [0.89427537]
 [0.88158557]]
Loss: 
0.0005777752375753295


# 697

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8979174 ]
 [0.8942648 ]
 [0.88158912]]
Loss: 
0.0005774868019097489


# 698

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89791923]
 [0.89425423]
 [0.88159267]]
Loss: 
0.0005771986322365203


# 699

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89792106]
 [0.89424367]
 [0.88159621]]
Loss: 
0.00057691072824154


# 700

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8979229 ]
 [0.89423312]
 [0.88159976]]
Loss: 
0.0005766230896110451


# 701

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89792473]
 [0.89422

# 797

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89810181]
 [0.89324473]
 [0.88193379]]
Loss: 
0.0005499355405295648


# 798

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89810366]
 [0.89323489]
 [0.88193714]]
Loss: 
0.0005496724404549449


# 799

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89810552]
 [0.89322506]
 [0.88194048]]
Loss: 
0.0005494095763567869


# 800

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89810737]
 [0.89321523]
 [0.88194382]]
Loss: 
0.0005491469479548967


# 801

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89810923]
 [0.89320541]
 [0.88194716]]
Loss: 
0.0005488845549693982


# 802

Input (scaled): 
[[0.4 0.9]
 [0.2

Predicted Output: 
[[0.89829366]
 [0.89226656]
 [0.88226781]]
Loss: 
0.0005240276901778118


# 901

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89829553]
 [0.89225741]
 [0.88227095]]
Loss: 
0.0005237874806463371


# 902

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8982974 ]
 [0.89224825]
 [0.88227409]]
Loss: 
0.0005235474799091865


# 903

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89829927]
 [0.89223911]
 [0.88227723]]
Loss: 
0.0005233076877186523


# 904

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89830114]
 [0.89222997]
 [0.88228036]]
Loss: 
0.0005230681038273452


# 905

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89830301]
 [0.892

 [0.89]]
Predicted Output: 
[[0.89847741]
 [0.89139819]
 [0.88256625]]
Loss: 
0.0005014429569862702


# 999

Input (scaled): 
[[0.4 0.9]
 [0.2 0.5]
 [0.6 0.6]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89847929]
 [0.89138962]
 [0.8825692 ]]
Loss: 
0.0005012220770798615


Predicted data based on trained weights: 
Input (scaled): 
[[1. 1.]]
Output: 
[[0.8832231]]
